### PR TITLE
hierarchical/tree argument type

### PR DESCRIPTION
**Pull request by djerius**
Barebones Tree/hierarchical argument type.

1. No docs
2. haven't tested cache
3. Not sure what to do for a more dynamic tree where individual nodes and leaves are dynamic rather than the whole tree (imagine hitting a database for each node). Should this class be made more extensible via inheritance, or kept simple?

### CODE REVIEW

**Comment by djerius** [comment]
requires PR #26

**Comment by sbakker** [comment]
I was thinking about similar things while cracking my Easter eggs. I prefer to keep the core as simple as possible. The caching of Enum values is still relatively simple, but for trees the possibilities are almost endless.

Simplest way is to accept a hashref, which may or may not be cached. If anything fancy needs to happen, it's up to the user to `tie` it to something more fancy... Otherwise, I wouldn't know how to make it generic in any way.

**Comment by sbakker** [comment]
Hi, do you think you will do further work on the tree argument type?

**Comment by djerius** [comment]
Whoops. Time sure does fly.  Yes, I'll clean this up.

**Comment by djerius** [comment]
A couple of notes:

1. The tests are running out of empty prefix ranges to keep the Argument tests together.  I didn't number the new ones.
2. The existing files seem to all need to be tidied.

**Comment by sbakker** [comment]
:+1: Thanks, I hope to have some time next week to review and merge.

**Pull request merged**
